Move platform-specific stuff to configure (avoid relying on GNU make) Autodetect gcc in configure Autodetect X11DIR in configure Rename PREFIX etc in line with GNU conventions
git-svn-id: svn://svn.code.sf.net/p/rdesktop/code/trunk/rdesktop@155 423420c4-83ab-492f-b58f-81f9feb106b5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,36 +7,75 @@
 
 echo "# Generated by $0 $*" >Makeconf
 
+
+# Choose gcc if available
+
+if `which gcc >/dev/null`; then
+    echo "CC          = gcc" >>Makeconf
+fi
+
+
+# Find X installation
+
+xdirs="/usr/X11 /usr/X11R6 /usr/openwin /usr /usr/local/X11 /usr/local/X11R6 /usr/local"
+
+for dir in $xdirs; do
+    if [ -e $dir/include/X11/Xlib.h ]; then
+	xdir=$dir
+	break
+    fi
+done
+
+if [ -z $xdir ]; then
+    echo "ERROR: could not find X installation"
+    echo "(searched for include/X11/Xlib.h in $xdirs)"
+    exit 1
+fi
+
+echo "X11DIR      = $xdir" >> Makeconf
+
+
+# Add platform-specific options
+
+case `uname -s` in
+  SunOS)
+    echo "LDFLAGS    += -R$(X11DIR)/lib -lsocket -lnsl" >>Makeconf
+    ;;
+esac
+
+
+# Process command line options
+
 for arg in $*; do
 optarg=`echo $arg | sed 's/[-a-z]*=//'`    
 case $arg in
   --prefix=*)
-    echo "PREFIX   = $optarg" >>Makeconf
+    echo "prefix      = $optarg" >>Makeconf
     ;;
   --exec-prefix=*)
-    echo "EPREFIX  = $optarg" >>Makeconf
+    echo "exec_prefix = $optarg" >>Makeconf
     ;;
   --bindir=*)
-    echo "BINDIR   = $optarg" >>Makeconf
+    echo "bindir      = $optarg" >>Makeconf
     ;;
   --mandir=*)
-    echo "MANDIR   = $optarg" >>Makeconf
+    echo "mandir      = $optarg" >>Makeconf
     ;;
   --sharedir=*)
-    echo "SHAREDIR   = $optarg" >>Makeconf
+    echo "datadir     = $optarg" >>Makeconf
     ;;
   --with-openssl*)
-    echo "CFLAGS  += -DWITH_OPENSSL" >>Makeconf
-    echo "LDLIBS  += -lcrypto" >>Makeconf
-    echo "CRYPTOBJ =" >>Makeconf
+    echo "CFLAGS     += -DWITH_OPENSSL" >>Makeconf
+    echo "LDFLAGS    += -lcrypto" >>Makeconf
+    echo "CRYPTOBJ    =" >>Makeconf
     ;;
   --without-openssl*)
     ;;
   --with-debug)
-    echo "CFLAGS  += -g -DWITH_DEBUG" >>Makeconf
+    echo "CFLAGS     += -g -DWITH_DEBUG" >>Makeconf
     ;;
   --with-debug-kbd)
-    echo "CFLAGS  += -g -DWITH_DEBUG_KBD" >>Makeconf
+    echo "CFLAGS     += -g -DWITH_DEBUG_KBD" >>Makeconf
     ;;
   --without-debug*)
     ;;
@@ -52,7 +91,7 @@ case $arg in
     echo
     echo "Build configuration:"
     echo " --with-openssl         use system OpenSSL libraries for crypto"
-    echo " --with-debug           enable debugging output"
+    echo " --with-debug           enable protocol debugging output"
     echo " --with-debug-kbd       enable debugging of keyboard handling"
     echo
     rm -f Makeconf
